export const spacesData = [
  {
    id: 1,
    categories: ["Lễ kỷ niệm", "Chính thức"],
    image: "/vmu/official/home-hero.jpg",
    date: "01/04/2026",
    name: "Lễ kỷ niệm 70 năm thành lập",
    location: "484 Lạch Tray, Hải Phòng",
    clientImage: "/logos/Logo-truong.png",
    clientName: "VMU",
    route: "/tham-gia",
  },
  {
    id: 2,
    categories: ["Triển lãm", "Truyền thông"],
    image: "/vmu/official/event-1.jpg",
    date: "03-04/2026",
    name: "Không gian truyền thông và triển lãm chủ đề 70 năm",
    location: "Khuôn viên VMU, Hải Phòng",
    clientImage: "/logos/Logo-truong.png",
    clientName: "VMU",
    route: "/thu-vien",
  },
  {
    id: 3,
    categories: ["Triển lãm", "Lịch sử"],
    image: "/vmu/official/about-history-1.jpg",
    date: "03/2026",
    name: "Triển lãm tư liệu và dấu mốc phát triển VMU",
    location: "Không gian trưng bày VMU",
    clientImage: "/logos/Logo-truong.png",
    clientName: "VMU",
    route: "/thu-vien",
  },
  {
    id: 4,
    categories: ["Lễ kỷ niệm", "Vinh danh"],
    image: "/vmu/official/event-2.jpg",
    date: "01/04/2026",
    name: "Lễ vinh danh tập thể và cá nhân tiêu biểu",
    location: "Hội trường lớn VMU",
    clientImage: "/logos/Logo-truong.png",
    clientName: "VMU",
    route: "/tham-gia",
  },
  {
    id: 5,
    categories: ["Cộng đồng", "Kết nối"],
    image: "/vmu/official/event-3.jpg",
    date: "01/04/2026",
    name: "Gặp mặt cựu sinh viên, đối tác và cộng đồng VMU",
    location: "Khuôn viên VMU, Hải Phòng",
    clientImage: "/logos/Logo-truong.png",
    clientName: "Cộng đồng VMU",
    route: "/tham-gia",
  },
  {
    id: 6,
    categories: ["Triển lãm", "Nghiên cứu"],
    image: "/vmu/official/about-history-2.jpg",
    date: "03/2026",
    name: "Không gian thành tựu nghiên cứu và chuyển giao",
    location: "Khối học thuật VMU",
    clientImage: "/logos/Logo-truong.png",
    clientName: "VMU",
    route: "/thu-vien",
  },
  {
    id: 7,
    categories: ["Tầm nhìn", "Chiến lược"],
    image: "/vmu/official/about-history-3.jpg",
    date: "01/04/2026",
    name: "Công bố định hướng phát triển 2030 - 2045",
    location: "Hội trường VMU",
    clientImage: "/logos/Logo-truong.png",
    clientName: "VMU",
    route: "/tam-nhin",
  },
];
