export const spacesData = [
  {
    id: 1,
    categories: ["Lễ kỷ niệm", "Chính thức"],
    image: "/spaces/space-1.jpg",
    date: "05/09/2025",
    name: "Lễ kỷ niệm 70 năm thành lập VMU",
    location: "Hải Phòng, Việt Nam",
    clientImage: "/spaces/client-1.jpeg",
    clientName: "VMU",
    route: "/sample-space",
  },
  {
    id: 2,
    categories: ["Hội thảo", "Quốc tế"],
    image: "/spaces/space-2.jpg",
    date: "15/10/2025",
    name: "Hội thảo Kinh tế biển bền vững",
    location: "Hà Nội, Việt Nam",
    clientImage: "/spaces/client-2.jpeg",
    clientName: "Bộ GTVT",
    route: "/sample-space",
  },
  {
    id: 3,
    categories: ["Triển lãm", "Lịch sử"],
    image: "/spaces/space-3.jpg",
    date: "20/11/2025",
    name: "Triển lãm 70 năm phát triển VMU",
    location: "TP.HCM, Việt Nam",
    clientImage: "/spaces/client-3.jpeg",
    clientName: "VMU Alumni",
    route: "/sample-space",
  },
  {
    id: 4,
    categories: ["Hội thảo", "Khoa học"],
    image: "/spaces/space-4.jpg",
    date: "10/12/2025",
    name: "Hội thảo Công nghệ hàng hải 4.0",
    location: "Đà Nẵng, Việt Nam",
    clientImage: "/spaces/client-4.jpeg",
    clientName: "IMO",
    route: "/sample-space",
  },
  {
    id: 5,
    categories: ["Lễ kỷ niệm", "Alumni"],
    image: "/spaces/space-5.jpg",
    date: "25/01/2026",
    name: "Gặp mặt Cựu sinh viên VMU",
    location: "Hải Phòng, Việt Nam",
    clientImage: "/spaces/client-5.jpeg",
    clientName: "VMU Alumni",
    route: "/sample-space",
  },
  {
    id: 6,
    categories: ["Hội thảo", "Đối tác"],
    image: "/spaces/space-6.jpg",
    date: "15/02/2026",
    name: "Hội thảo Hợp tác quốc tế",
    location: "Singapore",
    clientImage: "/spaces/client-6.jpeg",
    clientName: "ASEAN",
    route: "/sample-space",
  },
  {
    id: 7,
    categories: ["Triển lãm", "Tương lai"],
    image: "/spaces/space-7.jpg",
    date: "01/04/2026",
    name: "Triển lãm Tầm nhìn 2045",
    location: "Hải Phòng, Việt Nam",
    clientImage: "/spaces/client-7.jpeg",
    clientName: "VMU",
    route: "/sample-space",
  },
];
